---
output:
  pdf_document: default
---
# Pipeline

Todo lo anterior se puede plantear de una manera específica. 
Utilizando métodos ...

## Construcción de Base de Datos
El presente estudio busca aplicar herramientas de aprendizaje estadístico para predecir la expansión urbana de la Zona Metropolitana de Chihuahua a través de características geográficas y demográficas y económicas descritas a continuación.

Debido a la naturaleza de la información de las variables se propusó crear un grid de hexagonos que cubran toda el área de influencia del modelo, en este caso la zona metropolitana de Chihuahua. De esta forma se organiza la información relevante obtenida a través de distintas fuentes dentro del grid de tal manera que cada hexagono posee la información asociada a cada área. Además a cada hexagono se le asigna una variable que indica si pertenece o no a la mancha urbana representada por los ageb urbanos.

Se decidió generar el grid con hexagonos dado a la naturaleza de las variables.
Explicar porqué los hexagonos!!!!


Construcción del grid:
- Grid:grid de hexagonos que cubran toda el área de influencia del modelo de 
      250 metros x 250 metros.
- Área de influencia: Será sobre la cual se realiza la modelación y se asume que el crecimiento no superará esta área de influencia. Para Chihuahua, se consideró un radio de 7,000 metros.

sistema de coordenadas UTM de la zona 13 Norte, Datum WGS84!!!!

Herramientas utilizadas:
PostGIS: extensión de la base de datos PostgreSQL que permite gestionar objetos geográficos, donde se utliza PostgreSQL (cita) como base de datos espacial en un Sistema de Información Geográfica (SIG) ^[Ha sido desarrollado por _Refraction Research_ como un proyecto de software libre bajo licencia GLP.].



### Datos demográficos
Se utilizó la información de los censos 2000 y 2010, junto con la del conteo del 2005 [@inegi] a nivel AGEB ^[Área Geográfica Básica: explicar ageb].

se realizó el siguiente procedimiento:

a. Se realizó una transformación de coordenadas correspondientes para tener tanto el shapefile de los AGEB como la malla dentro de las mismas unidades, en este caso UTM zona 13 Norte.  

b. Se calculó el área de cada AGEB en metros.  

c. Se intersectó el shapefile de AGEBs con la malla cuadriculada como se muestra en la siguiente figura. Utilizando esta intersección, se le agregó a la malla las variables elegidas del censo de población y vivienda (o conteo para 2005) de acuerdo a la proporción de área del AGEB que intersecta a cada cuadrícula.   

d. Para realizarlo, primero se calculó el área de cada polígono de la intersección y se obtuvo la proporción de área que le corresponde a cada polígono de la intersección con respecto al área total del AGEB al que corresponde.   

e. A partir de las proporciones de área de cada polígono con respecto al área total de AGEB que le corresponde, se calculó la proporción correspondiente para cada variable. Si la variable correspondía a una cantidad total dentro del AGEB, entonces esta variable se multiplicó por la proporción de área obtenida en el inciso (f), mientras que en el caso en el que la variable correspondiera a un promedio entonces se le asoció al polígono el dato del AGEB correspondiente.   

f. A la tabla de atributos de la malla se le agregaron las variables de interés de SCINCE. Para realizar esto, se sumó o promedió, de acuerdo al tipo de variable, la información de los polígonos de la intersección que caían dentro de una misma cuadrícula del grid.   

Después de haber incluido las variables de las AGEB urbanas dentro de la malla, se agregó la misma información las localidades rurales que caen dentro del área de influencia (la malla). Para esto, se utilizó la información proveniente de los principales resultados por localidad (ITER) de 2000, 2005 y 2010 (INEGI) y agregaron dentro de la malla de la siguiente manera:


i) Primero se corrigieron y homologaron las coordenadas que vienen reportadas en el ITER, debido a que estas coordenadas vienen reportadas en grados, minutos y segundos, además se corrigió el signo de la latitud. De esta manera se pudo obtener el sistema de coordenadas geográficas de las localidades [en CRS(“+proj=longlat +datum=WGS84”)]para generar un shapefile. Después de ser proyectado, se transformaron las coordenadas en UTM zona 13 para hacerlo coincidir con la malla.

ii) Debido a que existían diferencias en la ubicación de una misma localidad para los distintos años, esto a causa principalmente de los cambios en la precisión de los GPS, se siguen los siguientes pasos para corregir la información:  

a) A las localidades rurales de 2000 y 2005 que se ubicaran en coordenadas distintas a las de 2010, se reubicaron de acuerdo a las coordenadas de 2010. De esta forma una misma localidad coincidirá en coordenadas para los tres años. El motivo de reasignarlo a las coordenadas de 2010 se debe a que la precisión de los GPS’s ha aumentado; por lo que las coordenadas de 2010 tendrán una precisión mayor.   

b) Siguiendo la misma lógica para las localidades rurales que en el año 2000 se encontraran en distintas coordenadas que en 2005 y además que no se encontraran en 2010, ya sea porque se unieron a una localidad urbana o simplemente desparecieron,  entonces a esas las localidades de 2000 se les reasignaron sus coordenadas a las de 2005.   

c)  Por último, si una localidad rural se encontraba en 2000 y en 2010 pero no en 2005, entonces se generó la información de esa localidad para 2005 tomando los valores promedio de 2000 y 2010. 

iii) Una vez homogeneizando las coordenadas, se incluyó la información del los las localidades rurales a la malla de la siguiente manera:

a) Se eligieron las variables de interés (las mismas de los AGEB urbanos incluidas en las mallas para 2000, 2005 y 2010). Se eliminaron las localidades con población mayor a 2,500 habitantes, puesto que estas ya son localidades urbanas y su información se encuentra incluida en los AGEB urbanos.  

b) Se intersectó el shapefile de las localidades rurales con la malla (se hizo lo mismo para los tres periodos) y se le asignó la información de las localidades a las cuadrículas que intersectaran los puntos de las localidades. Si dos localidades caían dentro de una misma cuadrícula, entonces se sumaron o promediaron los valores según el tipo de variable (total o promedio). Además, si en una cuadrícula en donde ya existía información de las AGEB urbanas intersecta una localidad rural, entonces de igual manera se suman o promedian los valores.  

Utilizando la información de las localidades rurales, se incluyó a la malla la distancia mínima, en metros, del centro de cada cuadrícula a la localidad rural más cercana.  Esta variable fue incluida debido a que se considera que las localidades rurales cercanas a la zona urbana tienden a migrar en busca de trabajo y servicios. 

### Económicos

**_Unidades Económicas_**    

Cercanía a unidades económicas (DENUE) y al centro urbano

la distancia de cada cuadrícula a las unidades económicas grandes y medianas que se encuentran en el Directorio Estadístico Nacional de Unidades Económicas (DENUE). Para realizar esto primero se consideran unidades económicas grandes a las que registren tener a más de 250 empleados y medianas a las que registren entre 51 y 250 empleados. A partir de estas unidades se calculó la distancia mínima en metros que hay desde el centro de cada cuadrícula a estas unidades.

!! No hay datos para antes del 2008, por lo que se asume que no han cambiado, sin embargo deberían considerarse únicamente las unidades ecónomicas existentes para cada periodo.

**_Centro Urbano_**    

El centro urbano de la ciudad, se caracteriza por concentrar comercios y servicios de escala urbana en la ciudad y ser sede de las oficinas de gobierno \cite{IMPLAN}. Por lo que se utiliza la distancia a dicho centro como una variable que influye en la expansión. 

Para calcular la distancia hay centro urbano, primero se encontraron las coordenadas del centro urbano [@googlemaps] y se expandió hasta un radio de 1 km, donde se considera que se acumulan las principales actividades económicas del centro urbano. A partir de ese radio se calculo la mínima distancia en metros que hay desde el centro de cada cuadrícula al centro urbano.

### Vías de Comunicación
Medir la accesibilidad de insumos y productos. La razón por la cual se incluye la distancia a carreteras, vías ferroviarias y aeropuerto.

**__Carreteras__**

Después se agregó la distancia que hay de cada cuadrícula a las carreteras o vías princiaples (INEGI). 

La distancia se calculó como la distancia mínima que hay desde el centroide de cada cuadrícula a la red carretera o vías principales.
Se consideraron las siguientes vías:

- Carreteras
- Avenidas
- Calles

Además se tomó la distancia mínima a las vías por tipo de derecho: libres o de cuota.Y por número de carriles: 1, 2 y 4 carriles


**__Vías Férreas_**
Las vías ferroviarias en el país son pocas --- bla bla una breve descripción de cómo conectan. Eje norte-sur (Ciudad Juárez - México D.F.) y superponiente-nororiente (Cuauhtémoc - Ojinaga). ¿Quién las utiliza?
Es notable el uso de un sector de la población que reside al norte de la ciudad como vialidad primaria \cite{IMPLAN}. 

### Geográficos

Se asienta en un valle definido por serranías en los 4 puntos cardinales, así como por dos escurrimientos naturales principales o ríos.
Tomando como centro el área que ocupa actualmente el centro urbano de la ciudad se tienen los siguientes límites o barreras naturales:
• Al poniente la Sierra del Mogote con alturas de hasta 2000 m.s.n.m.
• Al oriente la Sierra de Nombre de Dios o Cerros Colorados, más al oriente de esta, quedando en medio el valle del río Chuvíscar que actualmente acoge a la zona nororiente de la ciudad, las Sierras de San Ignacio y de Santa Eulalia
• Al norte el valle de Chihuahua se abre por en medio de las Sierras del Mogote y de Nombre de Dios / Cerros Colorados
• Al sur la Sierra Azul
Todas las sierras referidas se consideran zonas no urbanizables debido a que cuentan con pendientes iguales o superiores al 20%.

De esta manera existe una división del espacio natural de la ciudad determinada por la extensión de la Sierra de Nombre de Dios y las elevaciones aisladas hasta casi tocar o ser parte el cerro Grande de la Sierra Azul al sur. Tanto el Cerro Grande como el Coronel son considerados por el PDU 2000 como zonas con potencial para decretarse patrimonio natural, e inclusive forman parte del escudo de armas de la capital. (IMPLAN)


La pendiente se construyó a partir de la altura de los Modelos Digitales de Elevación (INEGI 2000 a escala de 1:250 metros) la cual viene en formato raster.  

Se extrajo la información del raster para incluirla a la malla por medio una función que se aplica a los valores del raster (pixeles) que caen dentro de una misma cuadrícula. Se crearon tres varibles distintas una para cada función: 
- slope_mean: utilizando el promedio   
- slope_med: utilizando la mediana   
- slope_max: utilizando el máximo   

Después de las variables económicas se agregó una variable que indica el tipo de uso de suelo al que pertenece cada cuadrícula, de acuerdo con las Capas de Uso de Suelo III, IV y V de INEGI(a escala 1:250 000) para cada una de las mallas del año que le corresponda. La información de las capas de uso de suelo muestra la distribución geográfica de los diferentes tipos de vegetación natural (primaria y secundaria) y de la vegetación inducida. La variable se agregó de la siguiente manera:

i) Con la información de INEGi de las capas de uso de suelo:   
- Serie III de 2002-2005 con año de referencia 2002 que utiliza imágenes LANDSATTM (30m)   
- Serie IV de 2006-2010 con año de referencia 2007 que utiliza imágenes SPOT 5 (10m).   
- Serie V de 2011- 2013 con año de referencia 2011 que utiliza imágenes LANDSAT (30m)   
ii) Las categorías de las capas de uso de suelo de las tres series, se reclasificaron y agruparon en 10 categorías, mostradas en la tabla siguiente:   



### Label
Con el fin de poder medir las causas de expansión urbana, se define en este trabajo la  variable de interés (a predecir)  como un cambio en el uso de suelo de no-urbano a urbano, en un periodo de tiempo determinado.

## Modelos
Al realizar los modelos predictivos, se tomararán tres conjuntos de datos:

* Muestra de Entrenamiento: en este caso son los datos de 2000 $(t_{1})$ para predecir la mancha urbana de 2005 $(t_2)$. Estos datos son los que se utilizan para entrenar los modelos.
$$t_{1} \rightarrow t_{2}$$
* Muestra de Prueba: en este caso se utilizan los datos de 2005 $(t_{2})$ para predecir la mancha urbana de 2010 $(t_{3})$.Con esta muestra es posible comparar el desempeño de los diferentes modelos. Estos mismo datos nos darán el error real cometido con cada modelo. Esta comparación se realiza analizando qué tanto se ajustan los valores predichos a los reales.
$$ t_{2} \rightarrow t_{3} $$
* Muestra de Validación: son los datos que se utilizan para predecir 2015 $(t_{4})$.
$$ t_{3} \rightarrow t_{4} $$

Se corrieron los modelos:
- Regresión Lineal (grid parámetros)
- Bosque Aleatorio (grid parámetros)
- Extra Árboles (grid parámetros)
- 

Comparar con lo que se usa normalmente


 